/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsDrinkType,
} from '../models/index';
import {
    ModelsDrinkTypeFromJSON,
    ModelsDrinkTypeToJSON,
} from '../models/index';

export interface DrinksPresetsPostRequest {
    drinkType: ModelsDrinkType;
}

/**
 * 
 */
export class DrinksApi extends runtime.BaseAPI {

    /**
     * Creates request options for drinksPresetsGet without sending the request
     */
    async drinksPresetsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/drinks/presets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of all preset drinks
     * Get preset drinks
     */
    async drinksPresetsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsDrinkType>>> {
        const requestOptions = await this.drinksPresetsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsDrinkTypeFromJSON));
    }

    /**
     * Get a list of all preset drinks
     * Get preset drinks
     */
    async drinksPresetsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsDrinkType>> {
        const response = await this.drinksPresetsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for drinksPresetsPost without sending the request
     */
    async drinksPresetsPostRequestOpts(requestParameters: DrinksPresetsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['drinkType'] == null) {
            throw new runtime.RequiredError(
                'drinkType',
                'Required parameter "drinkType" was null or undefined when calling drinksPresetsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/drinks/presets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsDrinkTypeToJSON(requestParameters['drinkType']),
        };
    }

    /**
     * Create a new custom drink preset saving it to the database
     * Add custom drink preset
     */
    async drinksPresetsPostRaw(requestParameters: DrinksPresetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsDrinkType>> {
        const requestOptions = await this.drinksPresetsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsDrinkTypeFromJSON(jsonValue));
    }

    /**
     * Create a new custom drink preset saving it to the database
     * Add custom drink preset
     */
    async drinksPresetsPost(requestParameters: DrinksPresetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsDrinkType> {
        const response = await this.drinksPresetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
