/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsGame,
} from '../models/index';
import {
    ModelsGameFromJSON,
    ModelsGameToJSON,
} from '../models/index';

export interface GamesGetRequest {
    q: string;
}

/**
 * 
 */
export class GamesApi extends runtime.BaseAPI {

    /**
     * Creates request options for gamesGet without sending the request
     */
    async gamesGetRequestOpts(requestParameters: GamesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling gamesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/games`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search the cached Steam game list by name
     * Search games
     */
    async gamesGetRaw(requestParameters: GamesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsGame>>> {
        const requestOptions = await this.gamesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsGameFromJSON));
    }

    /**
     * Search the cached Steam game list by name
     * Search games
     */
    async gamesGet(requestParameters: GamesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsGame>> {
        const response = await this.gamesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
