/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlerBeerDTO,
  HandlerPatchPartyRequest,
  HandlerStringValue,
  ModelsPartyOption,
  ServicePartyDTO,
} from '../models/index';
import {
    HandlerBeerDTOFromJSON,
    HandlerBeerDTOToJSON,
    HandlerPatchPartyRequestFromJSON,
    HandlerPatchPartyRequestToJSON,
    HandlerStringValueFromJSON,
    HandlerStringValueToJSON,
    ModelsPartyOptionFromJSON,
    ModelsPartyOptionToJSON,
    ServicePartyDTOFromJSON,
    ServicePartyDTOToJSON,
} from '../models/index';

export interface PartiesCodeAttendeesAttendeeIdDeleteRequest {
    code: string;
    attendeeId: number;
}

export interface PartiesCodeAttendeesPostRequest {
    code: string;
    value: HandlerStringValue;
}

export interface PartiesCodeBeersPostRequest {
    code: string;
    beer: HandlerBeerDTO;
}

export interface PartiesCodeGetRequest {
    code: string;
}

export interface PartiesCodeOptionsGameNameDeleteRequest {
    code: string;
    gameName: string;
}

export interface PartiesCodeOptionsPostRequest {
    code: string;
    option: ModelsPartyOption;
}

export interface PartiesCodePatchRequest {
    code: string;
    patchReq: HandlerPatchPartyRequest;
}

export interface PartiesCodeStreamGetRequest {
    code: string;
    username: string;
}

export interface PartiesPostRequest {
    party: ServicePartyDTO;
}

/**
 * 
 */
export class PartiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for partiesCodeAttendeesAttendeeIdDelete without sending the request
     */
    async partiesCodeAttendeesAttendeeIdDeleteRequestOpts(requestParameters: PartiesCodeAttendeesAttendeeIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeAttendeesAttendeeIdDelete().'
            );
        }

        if (requestParameters['attendeeId'] == null) {
            throw new runtime.RequiredError(
                'attendeeId',
                'Required parameter "attendeeId" was null or undefined when calling partiesCodeAttendeesAttendeeIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/parties/{code}/attendees/{attendeeId}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));
        urlPath = urlPath.replace(`{${"attendeeId"}}`, encodeURIComponent(String(requestParameters['attendeeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an attendee from a party by index
     * Delete an attendee
     */
    async partiesCodeAttendeesAttendeeIdDeleteRaw(requestParameters: PartiesCodeAttendeesAttendeeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.partiesCodeAttendeesAttendeeIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an attendee from a party by index
     * Delete an attendee
     */
    async partiesCodeAttendeesAttendeeIdDelete(requestParameters: PartiesCodeAttendeesAttendeeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partiesCodeAttendeesAttendeeIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for partiesCodeAttendeesPost without sending the request
     */
    async partiesCodeAttendeesPostRequestOpts(requestParameters: PartiesCodeAttendeesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeAttendeesPost().'
            );
        }

        if (requestParameters['value'] == null) {
            throw new runtime.RequiredError(
                'value',
                'Required parameter "value" was null or undefined when calling partiesCodeAttendeesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties/{code}/attendees`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlerStringValueToJSON(requestParameters['value']),
        };
    }

    /**
     * Add an attendee to a party
     * Add an attendee
     */
    async partiesCodeAttendeesPostRaw(requestParameters: PartiesCodeAttendeesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlerStringValue>> {
        const requestOptions = await this.partiesCodeAttendeesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlerStringValueFromJSON(jsonValue));
    }

    /**
     * Add an attendee to a party
     * Add an attendee
     */
    async partiesCodeAttendeesPost(requestParameters: PartiesCodeAttendeesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlerStringValue> {
        const response = await this.partiesCodeAttendeesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesCodeBeersPost without sending the request
     */
    async partiesCodeBeersPostRequestOpts(requestParameters: PartiesCodeBeersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeBeersPost().'
            );
        }

        if (requestParameters['beer'] == null) {
            throw new runtime.RequiredError(
                'beer',
                'Required parameter "beer" was null or undefined when calling partiesCodeBeersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties/{code}/beers`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlerBeerDTOToJSON(requestParameters['beer']),
        };
    }

    /**
     * Add a beer for an attendee in a party
     * Add a beer
     */
    async partiesCodeBeersPostRaw(requestParameters: PartiesCodeBeersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.partiesCodeBeersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a beer for an attendee in a party
     * Add a beer
     */
    async partiesCodeBeersPost(requestParameters: PartiesCodeBeersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partiesCodeBeersPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for partiesCodeGet without sending the request
     */
    async partiesCodeGetRequestOpts(requestParameters: PartiesCodeGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/parties/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a party by its code
     * Get a party
     */
    async partiesCodeGetRaw(requestParameters: PartiesCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePartyDTO>> {
        const requestOptions = await this.partiesCodeGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePartyDTOFromJSON(jsonValue));
    }

    /**
     * Get a party by its code
     * Get a party
     */
    async partiesCodeGet(requestParameters: PartiesCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePartyDTO> {
        const response = await this.partiesCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesCodeOptionsGameNameDelete without sending the request
     */
    async partiesCodeOptionsGameNameDeleteRequestOpts(requestParameters: PartiesCodeOptionsGameNameDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeOptionsGameNameDelete().'
            );
        }

        if (requestParameters['gameName'] == null) {
            throw new runtime.RequiredError(
                'gameName',
                'Required parameter "gameName" was null or undefined when calling partiesCodeOptionsGameNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/parties/{code}/options/{gameName}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));
        urlPath = urlPath.replace(`{${"gameName"}}`, encodeURIComponent(String(requestParameters['gameName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an option from a party by its name
     * Delete an option
     */
    async partiesCodeOptionsGameNameDeleteRaw(requestParameters: PartiesCodeOptionsGameNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.partiesCodeOptionsGameNameDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an option from a party by its name
     * Delete an option
     */
    async partiesCodeOptionsGameNameDelete(requestParameters: PartiesCodeOptionsGameNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partiesCodeOptionsGameNameDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for partiesCodeOptionsPost without sending the request
     */
    async partiesCodeOptionsPostRequestOpts(requestParameters: PartiesCodeOptionsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeOptionsPost().'
            );
        }

        if (requestParameters['option'] == null) {
            throw new runtime.RequiredError(
                'option',
                'Required parameter "option" was null or undefined when calling partiesCodeOptionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties/{code}/options`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsPartyOptionToJSON(requestParameters['option']),
        };
    }

    /**
     * Add an option to a party
     * Add an option
     */
    async partiesCodeOptionsPostRaw(requestParameters: PartiesCodeOptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsPartyOption>> {
        const requestOptions = await this.partiesCodeOptionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsPartyOptionFromJSON(jsonValue));
    }

    /**
     * Add an option to a party
     * Add an option
     */
    async partiesCodeOptionsPost(requestParameters: PartiesCodeOptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsPartyOption> {
        const response = await this.partiesCodeOptionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesCodePatch without sending the request
     */
    async partiesCodePatchRequestOpts(requestParameters: PartiesCodePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodePatch().'
            );
        }

        if (requestParameters['patchReq'] == null) {
            throw new runtime.RequiredError(
                'patchReq',
                'Required parameter "patchReq" was null or undefined when calling partiesCodePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: HandlerPatchPartyRequestToJSON(requestParameters['patchReq']),
        };
    }

    /**
     * Update a party status
     * Patch a party
     */
    async partiesCodePatchRaw(requestParameters: PartiesCodePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePartyDTO>> {
        const requestOptions = await this.partiesCodePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePartyDTOFromJSON(jsonValue));
    }

    /**
     * Update a party status
     * Patch a party
     */
    async partiesCodePatch(requestParameters: PartiesCodePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePartyDTO> {
        const response = await this.partiesCodePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesCodeStreamGet without sending the request
     */
    async partiesCodeStreamGetRequestOpts(requestParameters: PartiesCodeStreamGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeStreamGet().'
            );
        }

        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling partiesCodeStreamGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/parties/{code}/stream`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Opens a Server-Sent Events stream for real-time party updates
     * SSE stream for a party
     */
    async partiesCodeStreamGetRaw(requestParameters: PartiesCodeStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.partiesCodeStreamGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Opens a Server-Sent Events stream for real-time party updates
     * SSE stream for a party
     */
    async partiesCodeStreamGet(requestParameters: PartiesCodeStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.partiesCodeStreamGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesGet without sending the request
     */
    async partiesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/parties`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all parties ordered by ID
     * Get all parties
     */
    async partiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServicePartyDTO>>> {
        const requestOptions = await this.partiesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServicePartyDTOFromJSON));
    }

    /**
     * Get all parties ordered by ID
     * Get all parties
     */
    async partiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServicePartyDTO>> {
        const response = await this.partiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partiesPost without sending the request
     */
    async partiesPostRequestOpts(requestParameters: PartiesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['party'] == null) {
            throw new runtime.RequiredError(
                'party',
                'Required parameter "party" was null or undefined when calling partiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServicePartyDTOToJSON(requestParameters['party']),
        };
    }

    /**
     * Creates a new party with a generated 6-character code
     * Create a new party
     */
    async partiesPostRaw(requestParameters: PartiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicePartyDTO>> {
        const requestOptions = await this.partiesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicePartyDTOFromJSON(jsonValue));
    }

    /**
     * Creates a new party with a generated 6-character code
     * Create a new party
     */
    async partiesPost(requestParameters: PartiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicePartyDTO> {
        const response = await this.partiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
