// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePartyData, CreatePartyResponses, DeleteAttendeeData, DeleteAttendeeResponses, DeleteOptionData, DeleteOptionResponses, GetDrinkTypesData, GetDrinkTypesResponses, GetPartiesData, GetPartiesResponses, GetPartyData, GetPartyResponses, GetUsersData, GetUsersResponses, LoginData, LoginResponses, PatchPartyData, PatchPartyResponses, PostAttendeeData, PostAttendeeResponses, PostBeerData, PostBeerResponses, PostDrinkTypeData, PostDrinkTypeResponses, PostNextRoundData, PostNextRoundResponses, PostOptionData, PostOptionResponses, PostVoteData, PostVoteResponses, SearchGamesData, SearchGamesResponses, StreamPartyData, StreamPartyResponses, ValidateUserData, ValidateUserErrors, ValidateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get preset drinks
 *
 * Get a list of all preset drinks
 */
export const getDrinkTypes = <ThrowOnError extends boolean = false>(options?: Options<GetDrinkTypesData, ThrowOnError>) => (options?.client ?? client).get<GetDrinkTypesResponses, unknown, ThrowOnError>({ url: '/drinks/presets', ...options });

/**
 * Add custom drink preset
 *
 * Create a new custom drink preset saving it to the database
 */
export const postDrinkType = <ThrowOnError extends boolean = false>(options: Options<PostDrinkTypeData, ThrowOnError>) => (options.client ?? client).post<PostDrinkTypeResponses, unknown, ThrowOnError>({
    url: '/drinks/presets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search games
 *
 * Search the cached Steam game list by name
 */
export const searchGames = <ThrowOnError extends boolean = false>(options: Options<SearchGamesData, ThrowOnError>) => (options.client ?? client).get<SearchGamesResponses, unknown, ThrowOnError>({ url: '/games', ...options });

/**
 * Get all parties
 *
 * Get all parties ordered by ID
 */
export const getParties = <ThrowOnError extends boolean = false>(options?: Options<GetPartiesData, ThrowOnError>) => (options?.client ?? client).get<GetPartiesResponses, unknown, ThrowOnError>({ url: '/parties', ...options });

/**
 * Create a new party
 *
 * Creates a new party with a generated 6-character code
 */
export const createParty = <ThrowOnError extends boolean = false>(options: Options<CreatePartyData, ThrowOnError>) => (options.client ?? client).post<CreatePartyResponses, unknown, ThrowOnError>({
    url: '/parties',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a party
 *
 * Get a party by its code
 */
export const getParty = <ThrowOnError extends boolean = false>(options: Options<GetPartyData, ThrowOnError>) => (options.client ?? client).get<GetPartyResponses, unknown, ThrowOnError>({ url: '/parties/{code}', ...options });

/**
 * Patch a party
 *
 * Update a party status
 */
export const patchParty = <ThrowOnError extends boolean = false>(options: Options<PatchPartyData, ThrowOnError>) => (options.client ?? client).patch<PatchPartyResponses, unknown, ThrowOnError>({
    url: '/parties/{code}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add an attendee
 *
 * Add an attendee to a party
 */
export const postAttendee = <ThrowOnError extends boolean = false>(options: Options<PostAttendeeData, ThrowOnError>) => (options.client ?? client).post<PostAttendeeResponses, unknown, ThrowOnError>({
    url: '/parties/{code}/attendees',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an attendee
 *
 * Delete an attendee from a party by index
 */
export const deleteAttendee = <ThrowOnError extends boolean = false>(options: Options<DeleteAttendeeData, ThrowOnError>) => (options.client ?? client).delete<DeleteAttendeeResponses, unknown, ThrowOnError>({ url: '/parties/{code}/attendees/{attendeeId}', ...options });

/**
 * Add a beer
 *
 * Add a beer for an attendee in a party
 */
export const postBeer = <ThrowOnError extends boolean = false>(options: Options<PostBeerData, ThrowOnError>) => (options.client ?? client).post<PostBeerResponses, unknown, ThrowOnError>({
    url: '/parties/{code}/beers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Raise the round
 *
 * Start the next round for a party
 */
export const postNextRound = <ThrowOnError extends boolean = false>(options: Options<PostNextRoundData, ThrowOnError>) => (options.client ?? client).post<PostNextRoundResponses, unknown, ThrowOnError>({ url: '/parties/{code}/next-round', ...options });

/**
 * Add an option
 *
 * Add an option to a party
 */
export const postOption = <ThrowOnError extends boolean = false>(options: Options<PostOptionData, ThrowOnError>) => (options.client ?? client).post<PostOptionResponses, unknown, ThrowOnError>({
    url: '/parties/{code}/options',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an option
 *
 * Delete an option from a party by its name
 */
export const deleteOption = <ThrowOnError extends boolean = false>(options: Options<DeleteOptionData, ThrowOnError>) => (options.client ?? client).delete<DeleteOptionResponses, unknown, ThrowOnError>({ url: '/parties/{code}/options/{gameName}', ...options });

/**
 * SSE stream for a party
 *
 * Opens a Server-Sent Events stream for real-time party updates
 */
export const streamParty = <ThrowOnError extends boolean = false>(options: Options<StreamPartyData, ThrowOnError>) => (options.client ?? client).sse.get<StreamPartyResponses, unknown, ThrowOnError>({ url: '/parties/{code}/stream', ...options });

/**
 * Submit a vote
 *
 * Submit a vote for an attendee
 */
export const postVote = <ThrowOnError extends boolean = false>(options: Options<PostVoteData, ThrowOnError>) => (options.client ?? client).post<PostVoteResponses, unknown, ThrowOnError>({
    url: '/parties/{code}/votes/{attendee}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all users
 *
 * Returns a list of all registered users.
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({ url: '/users', ...options });

/**
 * Login or Register a User
 *
 * Logs in a user by username. If they do not exist, they are created.
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validate if a user exists
 *
 * Check if a user exists in the database by username
 */
export const validateUser = <ThrowOnError extends boolean = false>(options: Options<ValidateUserData, ThrowOnError>) => (options.client ?? client).get<ValidateUserResponses, ValidateUserErrors, ThrowOnError>({ url: '/users/{username}', ...options });
