// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/' | (string & {});
};

export type HandlerBeerDto = {
    attendee?: string;
};

export type HandlerPatchPartyRequest = {
    status?: string;
};

export type HandlerStringValue = {
    value?: string;
};

export type HandlerUserLoginRequest = {
    username: string;
};

export type ModelsDrinkType = {
    /**
     * Percentage, e.g., 5.0 for 5%
     */
    alcoholPercent?: number;
    /**
     * How many beers this equates to
     */
    beerEquivalent?: number;
    id?: string;
    name?: string;
    /**
     * e.g. "Halber Liter", "Shot", "Achtel"
     */
    unitName?: string;
    volumeMl?: number;
};

export type ModelsGame = {
    appId?: number;
    id?: string;
    imageUrl?: string;
    name?: string;
};

export type ModelsPartyOption = {
    appId?: number;
    imageUrl?: string;
    name?: string;
};

export type ServiceLink = {
    href?: string;
};

export type ServicePartyDto = {
    _links?: {
        [key: string]: ServiceLink;
    };
    attendees?: Array<string>;
    beerCount?: number;
    beerPerAttendee?: {
        [key: string]: number;
    };
    code?: string;
    id?: string;
    options?: Array<ModelsPartyOption>;
    results?: {
        [key: string]: number;
    };
    status?: string;
};

export type ServiceUserDto = {
    createdAt?: string;
    lastLogin?: string;
    username?: string;
};

export type GetDrinkTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/drinks/presets';
};

export type GetDrinkTypesResponses = {
    /**
     * OK
     */
    200: Array<ModelsDrinkType>;
};

export type GetDrinkTypesResponse = GetDrinkTypesResponses[keyof GetDrinkTypesResponses];

export type PostDrinkTypeData = {
    /**
     * Drink Type Details
     */
    body: ModelsDrinkType;
    path?: never;
    query?: never;
    url: '/drinks/presets';
};

export type PostDrinkTypeResponses = {
    /**
     * OK
     */
    200: ModelsDrinkType;
};

export type PostDrinkTypeResponse = PostDrinkTypeResponses[keyof PostDrinkTypeResponses];

export type SearchGamesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search Query
         */
        q: string;
    };
    url: '/games';
};

export type SearchGamesResponses = {
    /**
     * OK
     */
    200: Array<ModelsGame>;
};

export type SearchGamesResponse = SearchGamesResponses[keyof SearchGamesResponses];

export type GetPartiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties';
};

export type GetPartiesResponses = {
    /**
     * OK
     */
    200: Array<ServicePartyDto>;
};

export type GetPartiesResponse = GetPartiesResponses[keyof GetPartiesResponses];

export type CreatePartyData = {
    /**
     * Party details
     */
    body: ServicePartyDto;
    path?: never;
    query?: never;
    url: '/parties';
};

export type CreatePartyResponses = {
    /**
     * OK
     */
    200: ServicePartyDto;
};

export type CreatePartyResponse = CreatePartyResponses[keyof CreatePartyResponses];

export type GetPartyData = {
    body?: never;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query?: never;
    url: '/parties/{code}';
};

export type GetPartyResponses = {
    /**
     * OK
     */
    200: ServicePartyDto;
};

export type GetPartyResponse = GetPartyResponses[keyof GetPartyResponses];

export type PatchPartyData = {
    /**
     * Patch Request
     */
    body: HandlerPatchPartyRequest;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query?: never;
    url: '/parties/{code}';
};

export type PatchPartyResponses = {
    /**
     * OK
     */
    200: ServicePartyDto;
};

export type PatchPartyResponse = PatchPartyResponses[keyof PatchPartyResponses];

export type PostAttendeeData = {
    /**
     * Attendee Name
     */
    body: HandlerStringValue;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query?: never;
    url: '/parties/{code}/attendees';
};

export type PostAttendeeResponses = {
    /**
     * OK
     */
    200: HandlerStringValue;
};

export type PostAttendeeResponse = PostAttendeeResponses[keyof PostAttendeeResponses];

export type DeleteAttendeeData = {
    body?: never;
    path: {
        /**
         * Party Code
         */
        code: string;
        /**
         * Attendee Index
         */
        attendeeId: number;
    };
    query?: never;
    url: '/parties/{code}/attendees/{attendeeId}';
};

export type DeleteAttendeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostBeerData = {
    /**
     * Beer Details
     */
    body: HandlerBeerDto;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query?: never;
    url: '/parties/{code}/beers';
};

export type PostBeerResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostOptionData = {
    /**
     * Option Details
     */
    body: ModelsPartyOption;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query?: never;
    url: '/parties/{code}/options';
};

export type PostOptionResponses = {
    /**
     * OK
     */
    200: ModelsPartyOption;
};

export type PostOptionResponse = PostOptionResponses[keyof PostOptionResponses];

export type DeleteOptionData = {
    body?: never;
    path: {
        /**
         * Party Code
         */
        code: string;
        /**
         * Game Name
         */
        gameName: string;
    };
    query?: never;
    url: '/parties/{code}/options/{gameName}';
};

export type DeleteOptionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StreamPartyData = {
    body?: never;
    path: {
        /**
         * Party Code
         */
        code: string;
    };
    query: {
        /**
         * Username of the connected client
         */
        username: string;
    };
    url: '/parties/{code}/stream';
};

export type StreamPartyResponses = {
    /**
     * OK
     */
    200: string;
};

export type StreamPartyResponse = StreamPartyResponses[keyof StreamPartyResponses];

export type PostVoteData = {
    /**
     * Choices (-1, 0, or 1)
     */
    body: {
        [key: string]: number;
    };
    path: {
        /**
         * Poll ID
         */
        code: string;
        /**
         * Attendee Name
         */
        attendee: string;
    };
    query?: never;
    url: '/parties/{code}/votes/{attendee}';
};

export type PostVoteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<ServiceUserDto>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type LoginData = {
    /**
     * Login Request
     */
    body: HandlerUserLoginRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ServiceUserDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ValidateUserData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/users/{username}';
};

export type ValidateUserErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: unknown;
    };
};

export type ValidateUserError = ValidateUserErrors[keyof ValidateUserErrors];

export type ValidateUserResponses = {
    /**
     * OK
     */
    200: ServiceUserDto;
};

export type ValidateUserResponse = ValidateUserResponses[keyof ValidateUserResponses];
