/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerPatchPartyRequest
 */
export interface HandlerPatchPartyRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlerPatchPartyRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the HandlerPatchPartyRequest interface.
 */
export function instanceOfHandlerPatchPartyRequest(value: object): value is HandlerPatchPartyRequest {
    return true;
}

export function HandlerPatchPartyRequestFromJSON(json: any): HandlerPatchPartyRequest {
    return HandlerPatchPartyRequestFromJSONTyped(json, false);
}

export function HandlerPatchPartyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerPatchPartyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HandlerPatchPartyRequestToJSON(json: any): HandlerPatchPartyRequest {
    return HandlerPatchPartyRequestToJSONTyped(json, false);
}

export function HandlerPatchPartyRequestToJSONTyped(value?: HandlerPatchPartyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

