/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerStringValue
 */
export interface HandlerStringValue {
    /**
     * 
     * @type {string}
     * @memberof HandlerStringValue
     */
    value?: string;
}

/**
 * Check if a given object implements the HandlerStringValue interface.
 */
export function instanceOfHandlerStringValue(value: object): value is HandlerStringValue {
    return true;
}

export function HandlerStringValueFromJSON(json: any): HandlerStringValue {
    return HandlerStringValueFromJSONTyped(json, false);
}

export function HandlerStringValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerStringValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function HandlerStringValueToJSON(json: any): HandlerStringValue {
    return HandlerStringValueToJSONTyped(json, false);
}

export function HandlerStringValueToJSONTyped(value?: HandlerStringValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

