/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsGame
 */
export interface ModelsGame {
    /**
     * 
     * @type {number}
     * @memberof ModelsGame
     */
    appId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsGame
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGame
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGame
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelsGame interface.
 */
export function instanceOfModelsGame(value: object): value is ModelsGame {
    return true;
}

export function ModelsGameFromJSON(json: any): ModelsGame {
    return ModelsGameFromJSONTyped(json, false);
}

export function ModelsGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsGame {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ModelsGameToJSON(json: any): ModelsGame {
    return ModelsGameToJSONTyped(json, false);
}

export function ModelsGameToJSONTyped(value?: ModelsGame | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        'id': value['id'],
        'imageUrl': value['imageUrl'],
        'name': value['name'],
    };
}

