/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelsPollStatus = {
    PollStatusInProgress: 'IN_PROGRESS',
    PollStatusCompleted: 'COMPLETED'
} as const;
export type ModelsPollStatus = typeof ModelsPollStatus[keyof typeof ModelsPollStatus];


export function instanceOfModelsPollStatus(value: any): boolean {
    for (const key in ModelsPollStatus) {
        if (Object.prototype.hasOwnProperty.call(ModelsPollStatus, key)) {
            if (ModelsPollStatus[key as keyof typeof ModelsPollStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelsPollStatusFromJSON(json: any): ModelsPollStatus {
    return ModelsPollStatusFromJSONTyped(json, false);
}

export function ModelsPollStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPollStatus {
    return json as ModelsPollStatus;
}

export function ModelsPollStatusToJSON(value?: ModelsPollStatus | null): any {
    return value as any;
}

export function ModelsPollStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ModelsPollStatus {
    return value as ModelsPollStatus;
}

