/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsUser
 */
export interface ModelsUser {
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    lastLogin?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    username?: string;
}

/**
 * Check if a given object implements the ModelsUser interface.
 */
export function instanceOfModelsUser(value: object): value is ModelsUser {
    return true;
}

export function ModelsUserFromJSON(json: any): ModelsUser {
    return ModelsUserFromJSONTyped(json, false);
}

export function ModelsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastLogin': json['lastLogin'] == null ? undefined : json['lastLogin'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ModelsUserToJSON(json: any): ModelsUser {
    return ModelsUserToJSONTyped(json, false);
}

export function ModelsUserToJSONTyped(value?: ModelsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'id': value['id'],
        'lastLogin': value['lastLogin'],
        'username': value['username'],
    };
}

