/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceLink
 */
export interface ServiceLink {
    /**
     * 
     * @type {string}
     * @memberof ServiceLink
     */
    href?: string;
}

/**
 * Check if a given object implements the ServiceLink interface.
 */
export function instanceOfServiceLink(value: object): value is ServiceLink {
    return true;
}

export function ServiceLinkFromJSON(json: any): ServiceLink {
    return ServiceLinkFromJSONTyped(json, false);
}

export function ServiceLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceLink {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function ServiceLinkToJSON(json: any): ServiceLink {
    return ServiceLinkToJSONTyped(json, false);
}

export function ServiceLinkToJSONTyped(value?: ServiceLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
    };
}

