/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PartiesCodeVotesAttendeePostRequest {
    code: string;
    attendee: string;
    choices: { [key: string]: number; };
}

/**
 * 
 */
export class PollsApi extends runtime.BaseAPI {

    /**
     * Creates request options for partiesCodeVotesAttendeePost without sending the request
     */
    async partiesCodeVotesAttendeePostRequestOpts(requestParameters: PartiesCodeVotesAttendeePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling partiesCodeVotesAttendeePost().'
            );
        }

        if (requestParameters['attendee'] == null) {
            throw new runtime.RequiredError(
                'attendee',
                'Required parameter "attendee" was null or undefined when calling partiesCodeVotesAttendeePost().'
            );
        }

        if (requestParameters['choices'] == null) {
            throw new runtime.RequiredError(
                'choices',
                'Required parameter "choices" was null or undefined when calling partiesCodeVotesAttendeePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/parties/{code}/votes/{attendee}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));
        urlPath = urlPath.replace(`{${"attendee"}}`, encodeURIComponent(String(requestParameters['attendee'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['choices'],
        };
    }

    /**
     * Submit a vote for an attendee
     * Submit a vote
     */
    async partiesCodeVotesAttendeePostRaw(requestParameters: PartiesCodeVotesAttendeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.partiesCodeVotesAttendeePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit a vote for an attendee
     * Submit a vote
     */
    async partiesCodeVotesAttendeePost(requestParameters: PartiesCodeVotesAttendeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partiesCodeVotesAttendeePostRaw(requestParameters, initOverrides);
    }

}
