/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlerUserLoginRequest,
  ModelsUser,
} from '../models/index';
import {
    HandlerUserLoginRequestFromJSON,
    HandlerUserLoginRequestToJSON,
    ModelsUserFromJSON,
    ModelsUserToJSON,
} from '../models/index';

export interface UsersPostRequest {
    req: HandlerUserLoginRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersGet without sending the request
     */
    async usersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of all registered users.
     * Get all users
     */
    async usersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsUser>>> {
        const requestOptions = await this.usersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsUserFromJSON));
    }

    /**
     * Returns a list of all registered users.
     * Get all users
     */
    async usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsUser>> {
        const response = await this.usersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersPost without sending the request
     */
    async usersPostRequestOpts(requestParameters: UsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['req'] == null) {
            throw new runtime.RequiredError(
                'req',
                'Required parameter "req" was null or undefined when calling usersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlerUserLoginRequestToJSON(requestParameters['req']),
        };
    }

    /**
     * Logs in a user by username. If they do not exist, they are created.
     * Login or Register a User
     */
    async usersPostRaw(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsUser>> {
        const requestOptions = await this.usersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUserFromJSON(jsonValue));
    }

    /**
     * Logs in a user by username. If they do not exist, they are created.
     * Login or Register a User
     */
    async usersPost(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsUser> {
        const response = await this.usersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
