/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerUserLoginRequest
 */
export interface HandlerUserLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlerUserLoginRequest
     */
    username: string;
}

/**
 * Check if a given object implements the HandlerUserLoginRequest interface.
 */
export function instanceOfHandlerUserLoginRequest(value: object): value is HandlerUserLoginRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function HandlerUserLoginRequestFromJSON(json: any): HandlerUserLoginRequest {
    return HandlerUserLoginRequestFromJSONTyped(json, false);
}

export function HandlerUserLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerUserLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function HandlerUserLoginRequestToJSON(json: any): HandlerUserLoginRequest {
    return HandlerUserLoginRequestToJSONTyped(json, false);
}

export function HandlerUserLoginRequestToJSONTyped(value?: HandlerUserLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

