/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerBeerDTO
 */
export interface HandlerBeerDTO {
    /**
     * 
     * @type {string}
     * @memberof HandlerBeerDTO
     */
    attendee?: string;
}

/**
 * Check if a given object implements the HandlerBeerDTO interface.
 */
export function instanceOfHandlerBeerDTO(value: object): value is HandlerBeerDTO {
    return true;
}

export function HandlerBeerDTOFromJSON(json: any): HandlerBeerDTO {
    return HandlerBeerDTOFromJSONTyped(json, false);
}

export function HandlerBeerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerBeerDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'attendee': json['attendee'] == null ? undefined : json['attendee'],
    };
}

export function HandlerBeerDTOToJSON(json: any): HandlerBeerDTO {
    return HandlerBeerDTOToJSONTyped(json, false);
}

export function HandlerBeerDTOToJSONTyped(value?: HandlerBeerDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendee': value['attendee'],
    };
}

