/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsPartyStatus } from './ModelsPartyStatus';
import {
    ModelsPartyStatusFromJSON,
    ModelsPartyStatusFromJSONTyped,
    ModelsPartyStatusToJSON,
    ModelsPartyStatusToJSONTyped,
} from './ModelsPartyStatus';

/**
 * 
 * @export
 * @interface ModelsParty
 */
export interface ModelsParty {
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsParty
     */
    attendees?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsParty
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsParty
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsParty
     */
    options?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsParty
     */
    pollId?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ModelsParty
     */
    results?: { [key: string]: number; };
    /**
     * 
     * @type {ModelsPartyStatus}
     * @memberof ModelsParty
     */
    status?: ModelsPartyStatus;
}



/**
 * Check if a given object implements the ModelsParty interface.
 */
export function instanceOfModelsParty(value: object): value is ModelsParty {
    return true;
}

export function ModelsPartyFromJSON(json: any): ModelsParty {
    return ModelsPartyFromJSONTyped(json, false);
}

export function ModelsPartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsParty {
    if (json == null) {
        return json;
    }
    return {
        
        'attendees': json['attendees'] == null ? undefined : json['attendees'],
        'code': json['code'] == null ? undefined : json['code'],
        'id': json['id'] == null ? undefined : json['id'],
        'options': json['options'] == null ? undefined : json['options'],
        'pollId': json['pollId'] == null ? undefined : json['pollId'],
        'results': json['results'] == null ? undefined : json['results'],
        'status': json['status'] == null ? undefined : ModelsPartyStatusFromJSON(json['status']),
    };
}

export function ModelsPartyToJSON(json: any): ModelsParty {
    return ModelsPartyToJSONTyped(json, false);
}

export function ModelsPartyToJSONTyped(value?: ModelsParty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendees': value['attendees'],
        'code': value['code'],
        'id': value['id'],
        'options': value['options'],
        'pollId': value['pollId'],
        'results': value['results'],
        'status': ModelsPartyStatusToJSON(value['status']),
    };
}

