/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelsPartyStatus = {
    PartyStatusNomination: 'NOMINATION',
    PartyStatusVoting: 'VOTING',
    PartyStatusResults: 'RESULTS'
} as const;
export type ModelsPartyStatus = typeof ModelsPartyStatus[keyof typeof ModelsPartyStatus];


export function instanceOfModelsPartyStatus(value: any): boolean {
    for (const key in ModelsPartyStatus) {
        if (Object.prototype.hasOwnProperty.call(ModelsPartyStatus, key)) {
            if (ModelsPartyStatus[key as keyof typeof ModelsPartyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelsPartyStatusFromJSON(json: any): ModelsPartyStatus {
    return ModelsPartyStatusFromJSONTyped(json, false);
}

export function ModelsPartyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPartyStatus {
    return json as ModelsPartyStatus;
}

export function ModelsPartyStatusToJSON(value?: ModelsPartyStatus | null): any {
    return value as any;
}

export function ModelsPartyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ModelsPartyStatus {
    return value as ModelsPartyStatus;
}

