/* tslint:disable */
/* eslint-disable */
/**
 * GameVote API
 * API for the GameVote application to manage parties, polls, and votes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceUserDTO
 */
export interface ServiceUserDTO {
    /**
     * 
     * @type {string}
     * @memberof ServiceUserDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceUserDTO
     */
    lastLogin?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceUserDTO
     */
    username?: string;
}

/**
 * Check if a given object implements the ServiceUserDTO interface.
 */
export function instanceOfServiceUserDTO(value: object): value is ServiceUserDTO {
    return true;
}

export function ServiceUserDTOFromJSON(json: any): ServiceUserDTO {
    return ServiceUserDTOFromJSONTyped(json, false);
}

export function ServiceUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'lastLogin': json['lastLogin'] == null ? undefined : json['lastLogin'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ServiceUserDTOToJSON(json: any): ServiceUserDTO {
    return ServiceUserDTOToJSONTyped(json, false);
}

export function ServiceUserDTOToJSONTyped(value?: ServiceUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'lastLogin': value['lastLogin'],
        'username': value['username'],
    };
}

